# Generated by Django 5.2.11 on 2026-02-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=100)),
                ("couser_name", models.CharField(max_length=100)),
                ("course_duration", models.IntegerField()),
                ("seat", models.IntegerField()),
            ],
        ),
    ]
